name: Run Java Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '21'

    - name: Build with Maven
      run: mvn clean install

    - name: Run Application and Generate Directories
      run: |
        java -cp target/classes org.example.App

    - name: Save Generated Directories
      uses: actions/upload-artifact@v2
      with:
        name: Graphs and Experiment
        path: |
          graphs
          experiments
